<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\DefinitionGenerator;

use TonyBogdanov\MagicServices\DefinitionGenerator;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait DefinitionGeneratorAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\DefinitionGenerator
 */
trait DefinitionGeneratorAwareTrait
{
    /** @var DefinitionGenerator $definitionGenerator */
    protected $definitionGenerator;

    /**
     * @return DefinitionGenerator
     */
    public function getDefinitionGenerator(): DefinitionGenerator
    {
        return $this->definitionGenerator;
    }

    /**
     * @required
     *
     * @param DefinitionGenerator $definitionGenerator
     *
     * @return $this
     */
    public function setDefinitionGenerator(DefinitionGenerator $definitionGenerator)
    {
        $this->definitionGenerator = $definitionGenerator;
        return $this;
    }
}
