<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\DefinitionGenerator;

use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;
use TonyBogdanov\MagicServices\DefinitionGenerator;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface DefinitionGeneratorAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\DefinitionGenerator
 */
interface DefinitionGeneratorAwareInterface extends ServiceAwareInterface
{
    /**
     * @return DefinitionGenerator
     *
     * @codeCoverageIgnore
     */
    public function getDefinitionGenerator(): DefinitionGenerator;

    /**
     * @required
     *
     * @param DefinitionGenerator $definitionGenerator
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setDefinitionGenerator(DefinitionGenerator $definitionGenerator);
}
