<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsServices;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait ParameterMagicServicesDefinitionsServicesAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsServices
 */
trait ParameterMagicServicesDefinitionsServicesAwareTrait
{
    /** @var array $parameterMagicServicesDefinitionsServices */
    protected $parameterMagicServicesDefinitionsServices;

    /**
     * @return array
     */
    public function getParameterMagicServicesDefinitionsServices(): array
    {
        return $this->parameterMagicServicesDefinitionsServices;
    }

    /**
     * @required
     *
     * @param array $parameterMagicServicesDefinitionsServices
     *
     * @return $this
     */
    public function setParameterMagicServicesDefinitionsServices(array $parameterMagicServicesDefinitionsServices)
    {
        $this->parameterMagicServicesDefinitionsServices = $parameterMagicServicesDefinitionsServices;
        return $this;
    }
}
