<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsPath;

use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface ParameterMagicServicesDefinitionsPathAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsPath
 */
interface ParameterMagicServicesDefinitionsPathAwareInterface extends ServiceAwareInterface
{
    /**
     * @return string
     */
    public function getParameterMagicServicesDefinitionsPath(): string;

    /**
     * @required
     *
     * @param string $parameterMagicServicesDefinitionsPath
     *
     * @return $this
     */
    public function setParameterMagicServicesDefinitionsPath(string $parameterMagicServicesDefinitionsPath);
}
