<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\AnnotationReader;

use Doctrine\Common\Annotations\Reader;
use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface AnnotationReaderAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\AnnotationReader
 */
interface AnnotationReaderAwareInterface extends ServiceAwareInterface
{
    /**
     * @return Reader
     */
    public function getAnnotationReader(): Reader;

    /**
     * @required
     *
     * @param Reader $annotationReader
     *
     * @return $this
     */
    public function setAnnotationReader(Reader $annotationReader);
}
