<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsAutoconfigure;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait ParameterMagicServicesDefinitionsAutoconfigureAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsAutoconfigure
 */
trait ParameterMagicServicesDefinitionsAutoconfigureAwareTrait
{
    /** @var bool $parameterMagicServicesDefinitionsAutoconfigure */
    protected $parameterMagicServicesDefinitionsAutoconfigure;

    /**
     * @return bool
     *
     * @codeCoverageIgnore
     */
    public function getParameterMagicServicesDefinitionsAutoconfigure(): bool
    {
        return $this->parameterMagicServicesDefinitionsAutoconfigure;
    }

    /**
     * @required
     *
     * @param bool $parameterMagicServicesDefinitionsAutoconfigure
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterMagicServicesDefinitionsAutoconfigure(bool $parameterMagicServicesDefinitionsAutoconfigure)
    {
        $this->parameterMagicServicesDefinitionsAutoconfigure = $parameterMagicServicesDefinitionsAutoconfigure;
        return $this;
    }
}
