<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterBag;

use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait ParameterBagAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterBag
 */
trait ParameterBagAwareTrait
{
    /** @var ParameterBagInterface $parameterBag */
    protected $parameterBag;

    /**
     * @return ParameterBagInterface
     *
     * @codeCoverageIgnore
     */
    public function getParameterBag(): ParameterBagInterface
    {
        return $this->parameterBag;
    }

    /**
     * @required
     *
     * @param ParameterBagInterface $parameterBag
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterBag(ParameterBagInterface $parameterBag)
    {
        $this->parameterBag = $parameterBag;
        return $this;
    }
}
