<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsAutowire;

use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface ParameterMagicServicesDefinitionsAutowireAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsAutowire
 */
interface ParameterMagicServicesDefinitionsAutowireAwareInterface extends ServiceAwareInterface
{
    /**
     * @return bool
     *
     * @codeCoverageIgnore
     */
    public function getParameterMagicServicesDefinitionsAutowire(): bool;

    /**
     * @required
     *
     * @param bool $parameterMagicServicesDefinitionsAutowire
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterMagicServicesDefinitionsAutowire(bool $parameterMagicServicesDefinitionsAutowire);
}
