<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareNamespace;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait ParameterMagicServicesAwareNamespaceAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareNamespace
 */
trait ParameterMagicServicesAwareNamespaceAwareTrait
{
    /** @var string $parameterMagicServicesAwareNamespace */
    protected $parameterMagicServicesAwareNamespace;

    /**
     * @return string
     *
     * @codeCoverageIgnore
     */
    public function getParameterMagicServicesAwareNamespace(): string
    {
        return $this->parameterMagicServicesAwareNamespace;
    }

    /**
     * @required
     *
     * @param string $parameterMagicServicesAwareNamespace
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterMagicServicesAwareNamespace(string $parameterMagicServicesAwareNamespace)
    {
        $this->parameterMagicServicesAwareNamespace = $parameterMagicServicesAwareNamespace;
        return $this;
    }
}
