<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsServices;

use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface ParameterMagicServicesDefinitionsServicesAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesDefinitionsServices
 */
interface ParameterMagicServicesDefinitionsServicesAwareInterface extends ServiceAwareInterface
{
    /**
     * @return array
     *
     * @codeCoverageIgnore
     */
    public function getParameterMagicServicesDefinitionsServices(): array;

    /**
     * @required
     *
     * @param array $parameterMagicServicesDefinitionsServices
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterMagicServicesDefinitionsServices(array $parameterMagicServicesDefinitionsServices);
}
