<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwarePath;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait ParameterMagicServicesAwarePathAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwarePath
 */
trait ParameterMagicServicesAwarePathAwareTrait
{
    /** @var string $parameterMagicServicesAwarePath */
    protected $parameterMagicServicesAwarePath;

    /**
     * @return string
     *
     * @codeCoverageIgnore
     */
    public function getParameterMagicServicesAwarePath(): string
    {
        return $this->parameterMagicServicesAwarePath;
    }

    /**
     * @required
     *
     * @param string $parameterMagicServicesAwarePath
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterMagicServicesAwarePath(string $parameterMagicServicesAwarePath)
    {
        $this->parameterMagicServicesAwarePath = $parameterMagicServicesAwarePath;
        return $this;
    }
}
