magic_services:
    definitions:
        path: '%kernel.project_dir%/config/magic_services.yaml'
        services:
            - '%kernel.project_dir%/src'
    aware:
        path: '%kernel.project_dir%/src/TonyBogdanov/MagicServices/DependencyInjection/Aware'
        namespace: 'TonyBogdanov\MagicServices\DependencyInjection\Aware'
        parameters:
            - regex: '/^magic_services\.(.+)$/i'
              name: 'ParameterMagicServices$1'
        services:
            - type: 'Doctrine\Common\Annotations\Reader'
              name: 'AnnotationReader'
            - 'Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
            - 'TonyBogdanov\MagicServices\CodeGenerator'
            - 'TonyBogdanov\MagicServices\AwareGenerator'
            - 'TonyBogdanov\MagicServices\DefinitionGenerator'
            - 'TonyBogdanov\MagicServices\Inspector'
