services:
    magic_services.inspector:
        class: TonyBogdanov\MagicServices\Inspector
        arguments:
            - '@Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface'
            - '%magic_services.aware.parameters%'
            - '%magic_services.aware.services%'

    magic_services.code_generator:
        class: TonyBogdanov\MagicServices\CodeGenerator

    magic_services.aware_generator:
        class: TonyBogdanov\MagicServices\AwareGenerator
        arguments:
            - '@magic_services.code_generator'
            - '%magic_services.aware.path%'
            - '%magic_services.aware.namespace%'

    magic_services.commands.aware.dump:
        class: TonyBogdanov\MagicServices\Command\Aware\Dump
        tags: [ 'console.command' ]
        arguments:
            - '@magic_services.inspector'
            - '@magic_services.aware_generator'

    magic_services.commands.aware.generate:
        class: TonyBogdanov\MagicServices\Command\Aware\Generate
        tags: [ 'console.command' ]
        arguments:
            - '@magic_services.inspector'
            - '@magic_services.aware_generator'
