<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareServices;

use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface ParameterMagicServicesAwareServicesAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareServices
 */
interface ParameterMagicServicesAwareServicesAwareInterface extends ServiceAwareInterface
{
    /**
     * @return array
     */
    public function getParameterMagicServicesAwareServices(): array;

    /**
     * @required
     *
     * @param array $parameterMagicServicesAwareServices
     *
     * @return $this
     */
    public function setParameterMagicServicesAwareServices(array $parameterMagicServicesAwareServices);
}
