<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareServices;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait ParameterMagicServicesAwareServicesAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareServices
 */
trait ParameterMagicServicesAwareServicesAwareTrait
{
    /** @var array $parameterMagicServicesAwareServices */
    protected $parameterMagicServicesAwareServices;

    /**
     * @return array
     *
     * @codeCoverageIgnore
     */
    public function getParameterMagicServicesAwareServices(): array
    {
        return $this->parameterMagicServicesAwareServices;
    }

    /**
     * @required
     *
     * @param array $parameterMagicServicesAwareServices
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterMagicServicesAwareServices(array $parameterMagicServicesAwareServices)
    {
        $this->parameterMagicServicesAwareServices = $parameterMagicServicesAwareServices;
        return $this;
    }
}
