<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\Inspector;

use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;
use TonyBogdanov\MagicServices\Inspector;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface InspectorAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\Inspector
 */
interface InspectorAwareInterface extends ServiceAwareInterface
{
    /**
     * @return Inspector
     */
    public function getInspector(): Inspector;

    /**
     * @required
     *
     * @param Inspector $inspector
     *
     * @return $this
     */
    public function setInspector(Inspector $inspector);
}
