<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\CodeGenerator;

use TonyBogdanov\MagicServices\CodeGenerator;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Trait CodeGeneratorAwareTrait
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\CodeGenerator
 */
trait CodeGeneratorAwareTrait
{
    /** @var CodeGenerator $codeGenerator */
    protected $codeGenerator;

    /**
     * @return CodeGenerator
     */
    public function getCodeGenerator(): CodeGenerator
    {
        return $this->codeGenerator;
    }

    /**
     * @required
     *
     * @param CodeGenerator $codeGenerator
     *
     * @return $this
     */
    public function setCodeGenerator(CodeGenerator $codeGenerator)
    {
        $this->codeGenerator = $codeGenerator;
        return $this;
    }
}
