<?php

namespace TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareNamespace;

use TonyBogdanov\MagicServices\Aware\ServiceAwareInterface;

/**
 * This file was automatically generated by the tonybogdanov/magic-services-bundle package.
 * Do not manually modify this file.
 *
 * Interface ParameterMagicServicesAwareNamespaceAwareInterface
 *
 * @package TonyBogdanov\MagicServices\DependencyInjection\Aware\ParameterMagicServicesAwareNamespace
 */
interface ParameterMagicServicesAwareNamespaceAwareInterface extends ServiceAwareInterface
{
    /**
     * @return string
     *
     * @codeCoverageIgnore
     */
    public function getParameterMagicServicesAwareNamespace(): string;

    /**
     * @required
     *
     * @param string $parameterMagicServicesAwareNamespace
     *
     * @return $this
     *
     * @codeCoverageIgnore
     */
    public function setParameterMagicServicesAwareNamespace(string $parameterMagicServicesAwareNamespace);
}
